site_name: PHI Masker Utils
theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jai-python3
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jsundaram/

repo_url: https://github.com/jai-python3/phi-masker-utils
repo_name: jai-python3/phi-masker-utils

plugins:
  - search
  - mkdocstrings:
      default_handler: python
nav:
  - Home: index.md
  - Installation: INSTALL.md
  - CHANGELOG: CHANGELOG.md
  - TODO: TODO.md
  - Code Reference:
  # INSERT CODE REFERENCE SECTION
    - Console Helper: console_helper.md
    - Constants: constants.md
    - File Utils: file_utils.md
    - Mask File: mask_file.md
    - Masker: masker.md
    - System Caller: system_caller.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/jai-python3"  target="_blank" rel="noopener">Jaideep Sundaram</a>
